project:
  type: website
  output-dir: .

website:
  twitter-card: true
  open-graph: true
  navbar:
        background: "black"
        foreground: "#FFFFFF"
        right:
         - href: about me.qmd
         - icon: linkedin
         - href: https://www.linkedin.com/in/yava-vilar-valera-496999271/
        left:
         - href: academic works.qmd
         - href: R.qmd

  page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with Quarto | R Studio

format:
  html:
    theme: [litera, styles.css]
    highlight-style: nord

execute:
  freeze: auto


