project:
  type: website
  output-dir: .

website:
  twitter-card: true
  open-graph: true
  navbar:
        background: "black"
        foreground: "#FFFFFF"
        right:
         - href: CV.qmd
         - href: about me.qmd
        left:
         - href: academic works.qmd

  page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with Quarto | RStudio

format:
  html:
    theme: [litera, styles.css]
    highlight-style: nord

execute:
  freeze: auto


