---
title: "International Double Degree Experience"
author: Yava Vilar Valera
date: 12/03/2021
toc: true
---

Irse a vivir, trabajar o estudiar fuera suele ser una experiencia que llama mucho la atención. Unos lo temen y prefieren evitarlo, otros lo idealizan y esperan aprender de ella un sinfín de cosas. Una de las maneras más comunes y fáciles hoy en día, si eres estudiante, de conseguir pasar un tiempo en el extranjero es a través de las becas Erasmus.

En mi caso, como estudiante de Economía en la Universidad de Valencia, quise participar en un programa de Doble Titulación Internacional con la Universidad de Nantes. Es decir, fue un intercambio de dos años en los que culminé mi carrera con los títulos de graduada de estas dos universidades. En mi universidad de destino me trataron como una estudiante propia de la universidad y seguí todas las clases e hice todos los exámenes con una promoción común, al igual que ocurrió durante mis dos primeros años en Valencia.

El programa que decidí escoger me intereso desde un principio ya que buscaba vivir fuera durante un tiempo prolongado. El francés es un idioma que ya conocía con anterioridad, lo cual facilito que me aceptaran en el programa, y siendo una persona a la que le gusta estudiar, quise añadir ese plus a mi carrera universitaria.

estudios

A las pocas semanas de llegar, me di cuenta de que cursar una Doble Titulación no solo requiere esfuerzo académico, sino también un gran compromiso personal. Es mucho más que estudiar en una nueva universidad: implica gestionar tu vida de forma independiente, desde las amistades que construyes hasta las decisiones y responsabilidades que asumes en lo cotidiano. Todo esto, en un entorno donde las costumbres, horarios y formas de comportarse son diferentes a lo que conocía.

En cuanto a la adaptación al país, esta fue relativamente sencilla para mí, ya que tenía conocimientos previos de francés y había vivido experiencias similares al mudarme anteriormente tanto dentro como fuera de mi país. Sin embargo, lo que realmente supuso un reto durante los primeros meses fue la exigencia académica. Ahí fue donde me di cuenta de la responsabilidad y el coraje necesarios para alcanzar altos objetivos mientras estudiaba en el extranjero. A medida que el tiempo pasaba y me adaptaba al nuevo sistema de aprendizaje, al ritmo de clases y examenes, se fue volviendo mas llevadero. No porque realmente el nivel de exigencia hubiera bajado, sino porque ya lo habia integrado en mi vida.

vida social

## Mi experiencia

A continuación dividiré mi experiencia en algunas categorías : la ciudad, vida social, estudios, y consejos que le daría a cualquier persona que quiera estudiar en el extranjero.

### La ciudad

Nantes es una ciudad situada en el noroeste de Francia, capital de la región Loire-Atlantique. Cuenta con mas de 300 000 habitantes y una gran vida universitaria. Para los españoles, Nantes podría ser considerada la Salamanca de Francia. Es una ciudad de tamaño medio, ni pequeña ni grande, aunque con mucho ocio, no necesitaras trasladarte a otras grandes ciudades para encontrar los servicios más comunes. A tres horas y media en coche de Burdeos y de Paris, se queda algo alejada de otras grandes ciudades del país, aunque hay bonitas ciudades más pequeñas que visitar a los alrededores como Rennes, La Rochelle, Angers, y pueblos con encanto y playa como Pornic. El clima deja algo que desear, ya que suele llover con frecuencia y estar nublado. Aun así, que no se exagere demasiado: también hay días de sol, y momentos de calor he pasado. Sin embargo, no suele ser suficiente. Un paraguas y vitamina D en pastillas sería una recomendación para vivir en esta ciudad. El transporte más común entre las personas jóvenes es el tranvía. Pasa con bastante frecuencia y está bien conectado, e incluso por las noches los fines de semana (viernes y sábados) hay servicio hasta las 2:30 de la madrugada y vuelve a funcionar desde las 4:30, lo cual es una ventaja si te gusta la vida nocturna. También hay autobuses y bicicletas que puedes alquilar. Durante los dos anos de mi estancia, estuve alojada en una habitación estudiantil en una residencia que la universidad reserva para los estudiantes internacionales. Se trata de una residencia publica gestionada por el CROUS, cuyo precio es asequible en comparación con el ámbito privado. Mi habitación tenía 9 metros cuadrados, un baño individual, una nevera y congelador, con cocina compartida. Aunque no era muy grande, conté con el espacio necesario para dormir, estudiar, moverme, e incluso en una ocasión dos amigas de España vinieron a visitarme y pudimos dormir tres personas en esos pocos metros cuadrados! En cuanto a deportes, Nantes hay muchas instalaciones deportivas cercanas a los campus universitarios y muchas opciones baratas para estudiantes. Un abono de 50 euros anuales permite a un estudiante practicar hasta tres deportes diferentes a la semana, dentro de una gran variedad de deportes que elegir. En mi caso, el primer año me inscribí a esta opción, hice escalada, bádminton y probe el gimnasio. El segundo ano opté por ir de vez en cuando a nadar de forma libre a una piscina para tal efecto cerca de mi facultad y residencia. Finalmente, los precios de Nantes son algo mas caros que en España, sobre todo a nivel de precio de alojamiento, comida, transporte y ocio, pero a nivel de servicios para estudiantes, suele ser mas asequible. Un ejemplo de ello es el deporte mencionado anteriormente. También se puede comer de lunes a viernes en un restaurante CROUS por 3,30 el menú. Además, hay mas ayudas publicas y las becas son mas generosas.

### Vida social

Mi vida social en Nantes ha sido bastante favorable ya que soy una persona a la que le gusta salir y hacer planes, y allí he conocido a personas con estos mismos intereses con las que he compartido muchos momentos de diversión y amistad. La gran cantidad de culturas que he conocido hizo mi estancia mucho mas interesante y enriquecedora. Irse a vivir fuera puede unirte mucho a personas de tu mismo pais o de otros paises que esten en la misma situacion que tu, ya que se crea un vinculo de apoyo mutuo en un entorno en el que esto se convierte en algo muy valorado.

En mi caso, el primer ano conoci a varias personas procedentes de varias culturas. Por un lado, me hice una amiga española que tenía su habitación a pocas puertas de la mía y que veía a menudo en una de las cocinas de mi residencia, cuya estancia en Nantes fue un ano. Por otro lado, hice buenos amigos de Colombia, que conocí por primera vez a los pocos días de llegar a Nantes en la cocina. Hoy en día sigue siendo mi amigo, aunque la distancia haga que ya no nos veamos físicamente. Cuando él regreso a Colombia, creé amistad con otro colombiano y empezamos a salir de vez en cuando de fiesta con estudiantes internacionales de la misma residencia: uno de Brasil, uno de Alemania, y tres del Líbano. Con ellos me lo pasé realmente bien, fueron las primeras veces que realmente sali con un grupo de chicos con los que me sentía cómoda y feliz. El curso siguiente este grupo se desvaneció ya que todos se fueron de la residencia, algunos regresaron a sus países y otros se mudaron porque la universidad ya no les renovaba una plaza en la residencia. Yo me quedé. Cuando volví en septiembre mi segundo año después de haber pasado el verano en Valencia, y vi que todas estas personas a las que había conocido ya no estaban, me sentí triste y nostálgica, pensando en que no volvería a verlos por los pasillos ni en mi residencia.

Pero la vida sigue adelante, los días fueron pasando, y de nuevo me fui creando nuevas amistades. Entré en un máster que entraba dentro de mi programa de intercambio, y ese ano que me esperaba me trajo muchos momentos increíbles y que disfruté muchísimo. Amigos franceses que a penas hice el primer ano, los hice en el máster, y fueron realmente simpáticas conmigo, me alegraron las clases e hice planes con ellas fuera de la universidad. Además, conocí a mucha gente latina: de México, Colombia, Ecuador, Venezuela, Perú… Havana café, en el centro de la ciudad, y el Sao, situado en la isla de Nantes, son los bares que se convirtieron en sitios fijos de ocio. Cada día que salía conocía a alguien nuevo, luego me los volvía a encontrar en el mismo sitio… y con ellos descubrí mi pasión por el baile latino. Bailábamos de manera informal bachata, salsa, merengue, y me encantaba. Luego me apunté a clases de salsa, lo cual me hizo conocer aun a mas gente. Al final, llego un momento en el que salía casi todos los fines de semana, excepto cuando tenia que estudiar mucho, y he tenido experiencias de todo tipo. Algunos momentos menos divertidos ha habido, pero en general, mi vida social en Nantes ha sido muy enriquecedora. Nantes tiene muchas opciones para jóvenes, gente abierta, comunidad latina, franceses a los que le gusta la marcha… ¡Es difícil aburrirse!

### Estudios

En Nantes, como destino erasmus, hay que estudiar. No es extremadamente difícil, pero si hay que esforzarse y dedicarle tiempo a la universidad. Esto en función de los objetivos académicos que tengas, por supuesto. Con revisar la asignatura y conocer lo fundamental de cada curso, no habrá problemas en aprobar. Además, algunos profesores son más generosos con los estudiantes erasmus, hacen exámenes orales individuales y puntúan de manera más flexible. Pero no todos. En mi caso, al estar cursando una doble titulación, me puntuaban como al resto de la clase y hacia siempre los mismos exámenes que ellos. Yo le dedique mucho tiempo al estudio. El primer ano que llegué, me estresé y me sentía insegura frente a la nueva dificultad. Bajé algo mis notas, lo cual me preocupo. Pero seguí esforzándome, porque me importaba. Y así, siguiendo a pesar de las dificultades, uno se adapta y eso que costaba al principio acaba convirtiéndose en algo no tan difícil. El segundo semestre mejoré mis notas, al igual que el segundo ano en el máster. Es importante mencionar que el sistema de notas y aprobados en Francia es diferente al de España. Para empezar, las notas van del 0 a 20, en lugar de 0 a 10. Con un 10 sobre 20, se considera aprobado. Sin embargo, a diferencia de España, las asignaturas se agrupan en bloques de dos o tres asignaturas, y si suspendes una de ellas, puedes compensar con la nota de otra asignatura del mismo bloque. Incluso suspendiendo un bloque entero, puedes compensar con la nota de otro bloque. A fin de cuentas, debes tener una media superior a 10 para pasar de curso sin necesidad de pasar por las recuperaciones. No obstante, a veces hay excepciones de asignaturas o trabajos que hay que aprobar de forma independiente, y que si no lo haces, deberás pasar otro examen, con un máximo de dos oportunidades.  La forma de corregir suele ser mas exigente que en España, y el nivel de dificultad de los exámenes puede variar. En mi caso, he sacado mas 18s/20 en Francia que 9s/10 en España, pero también mas 12s/20 en Francia que 6s/10 en España. En Nantes, he visto notas mas diversas en una misma persona que en Valencia. Digamos que la varianza de las notas en los estudiantes de Nantes es mayor que la de los estudiantes en Valencia, según lo que yo he visto en algunas personas y también en mi propio caso.
